language: php
matrix:
  include:
  - php: 5.5
  - php: 5.6
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm
sudo: false
cache:
  directories:
  - $HOME/.composer/cache
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_071e19cbf364_key -iv $encrypted_071e19cbf364_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- phpenv config-rm xdebug.ini
- composer selfupdate
install:
- travis_retry composer install --no-interaction $COMPOSER_FLAGS
- composer info -i
script:
- phpunit --coverage-text
notifications:
  email: true
after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi