language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text

notifications:
  email: lucas@cherifi.info
